language: cpp

# os:
#  - linux
#  - osx

compiler:
  - clang
  - gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:kubuntu-ppa/backports -y; fi; # cmake >=2.8.10
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi;

install:
  # install cmake
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq install cmake gcc-multilib g++-multilib valgrind; fi;

  # install boost
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libboost-dev libboost-all-dev; fi;

  # install g++
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-5; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50; fi

  # install clang
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then cwd=$(pwd); fi

before_script:
  - cmake --version
  - clang --version
  - gcc --version
  - mkdir build
  - cd build
  - cmake ..
  - cd ..

script:
  - cd build
  - make
  - cd ..

branches:
  except:
    - gh-pages

notifications:
  email: false

