language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - LIBSTDC_VERSION=5
    - CLANG_VERSION=3.6

matrix:
  include:
    os: linux
  allow_failures:
    - compiler: clang
    # - os: osx

before_install:
  # Setup cmake
  - sh scripts/install-cmake.sh

  # Prepare compiler
  - if [[ "$CXX" == "g++" || "$CC" == "gcc" ]]; then sh scripts/install-gcc.sh; fi
  - if [[ "$CXX" == "clang++" || "$CC" == "clang" ]]; then sh scripts/install-clang.sh; fi

  # Debug information
  - lsb_release -a
  - uname -a
  - cmake -version
  - $CC --version
  - $CXX --version

script:
  # Build with cmake
  - rm -rf build/
  - mkdir build
  - cd build
  - cmake ..
  - make

notifications:
  email: false

sudo: required

cache:
  - apt
